/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    articles: Article;
    'case-studies': CaseStudy;
    team: Team;
    'cta-config': CtaConfig;
    popups: Popup;
    categories: Category;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'cta-config': CtaConfigSelect<false> | CtaConfigSelect<true>;
    popups: PopupsSelect<false> | PopupsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'logo-wall': LogoWall;
    'voice-of-customer': VoiceOfCustomer;
  };
  globalsSelect: {
    'logo-wall': LogoWallSelect<false> | LogoWallSelect<true>;
    'voice-of-customer': VoiceOfCustomerSelect<false> | VoiceOfCustomerSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  publishedAt?: string | null;
  author?: (number | null) | User;
  coverImage?: (number | null) | Media;
  category?: (number | null) | Category;
  content: (
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        image: number | Media;
        caption?: string | null;
        alt: string;
        width?: ('full' | 'half' | 'inline') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        url: string;
        caption?: string | null;
        autoplay?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'video';
      }
    | {
        gif: number | Media;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gif';
      }
    | {
        text: string;
        author?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Used in URL filter params (e.g. company-news). Must be lowercase, hyphen-separated.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  coverImage?: (number | null) | Media;
  /**
   * e.g. "Novos Horizontes — Poultry Sector"
   */
  client?: string | null;
  /**
   * Category shown in the filter bar
   */
  tag?: ('Financial Inclusion' | 'EUDR Traceability' | 'Operational Efficiency') | null;
  /**
   * Bold card headline, e.g. "Unlocking $2M in Input Financing..."
   */
  headline?: string | null;
  /**
   * Challenge — what problem did the client face?
   */
  situation?: string | null;
  /**
   * Solution — what did eProd implement?
   */
  action?: string | null;
  /**
   * Impact — measurable outcome
   */
  result?: string | null;
  ctaLabel?: string | null;
  /**
   * URL the CTA button links to, e.g. /articles/my-story or https://...
   */
  ctaLink?: string | null;
  hasVideo?: boolean | null;
  /**
   * YouTube or Vimeo URL. Shown in the card cover when "Has Video" is checked.
   */
  videoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  title: string;
  photo: number | Media;
  bio: string;
  linkedin?: string | null;
  /**
   * Display order
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-config".
 */
export interface CtaConfig {
  id: number;
  title: string;
  email: {
    /**
     * Recipient email address
     */
    to: string;
    /**
     * Sender email address
     */
    from: string;
    /**
     * Email subject line
     */
    subject: string;
    /**
     * Use HTML content type
     */
    htmlContent?: boolean | null;
    /**
     * Email body. Use {company}, {email}, {challenge} for dynamic fields
     */
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Additional email headers
     */
    headers?:
      | {
          key: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * File attachments
     */
    attachments?: (number | Media)[] | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage popup notifications for trainings, webinars, and announcements. No code required — create and configure popups entirely from this panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups".
 */
export interface Popup {
  id: number;
  /**
   * Internal label to identify this popup (not visible to site visitors)
   */
  name: string;
  /**
   * Enable or disable this popup. Only active popups are shown on the site.
   */
  isActive?: boolean | null;
  /**
   * Optionally limit when this popup is shown. Leave both dates empty to always show it (while active).
   */
  scheduling?: {
    /**
     * Start showing from this date/time. Leave empty to start immediately.
     */
    startDate?: string | null;
    /**
     * Stop showing after this date/time. Leave empty to show indefinitely.
     */
    endDate?: string | null;
  };
  display: {
    /**
     * Which pages should this popup appear on.
     */
    pages: 'all' | 'homepage' | 'specific';
    /**
     * Enter exact page paths where the popup should appear (e.g. /about, /case-studies).
     */
    specificPaths?:
      | {
          path: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Seconds to wait after page load before showing the popup.
     */
    delay?: number | null;
    /**
     * How often this popup is shown to the same visitor.
     */
    frequency: 'every-visit' | 'once-per-session' | 'once-per-day' | 'once-per-week' | 'once-ever';
  };
  content: {
    /**
     * Optional small label shown above the title (e.g. "Upcoming Webinar", "Free Training").
     */
    badge?: string | null;
    /**
     * Main heading of the popup.
     */
    title: string;
    /**
     * Detailed popup content. Supports formatting, lists, and links.
     */
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Optional banner image shown at the top of the popup.
     */
    image?: (number | null) | Media;
  };
  /**
   * Action buttons displayed at the bottom of the popup. You can add multiple buttons.
   */
  buttons?:
    | {
        label: string;
        /**
         * What happens when this button is clicked.
         */
        action: 'link' | 'register' | 'close';
        /**
         * URL to open (required for "Open a Link" action).
         */
        url?: string | null;
        openInNewTab?: boolean | null;
        /**
         * Visual style of this button.
         */
        style?: ('primary' | 'secondary' | 'outline' | 'ghost') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Configures the form shown when a visitor clicks a "Register" button. The marketing team will receive an email for each registration.
   */
  registration?: {
    /**
     * Email address that receives registration notifications (e.g. marketing@eprod.com).
     */
    notifyEmail?: string | null;
    /**
     * Subject line for the notification email sent to your team.
     */
    emailSubject?: string | null;
    collectName?: boolean | null;
    collectPhone?: boolean | null;
    collectOrganization?: boolean | null;
    /**
     * Message shown to the visitor after they successfully register.
     */
    successMessage?: string | null;
  };
  appearance?: {
    /**
     * Maximum width of the popup.
     */
    size?: ('sm' | 'md' | 'lg') | null;
    /**
     * Allows visitors to dismiss the popup.
     */
    showCloseButton?: boolean | null;
    closeOnOverlayClick?: boolean | null;
    /**
     * Color of the badge label (if set).
     */
    badgeColor?: ('brand' | 'green' | 'blue' | 'orange' | 'purple' | 'red') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  company: string;
  email: string;
  challenge: string;
  sourceSection?: string | null;
  status?: ('new' | 'contacted' | 'qualified' | 'won' | 'lost') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'cta-config';
        value: number | CtaConfig;
      } | null)
    | ({
        relationTo: 'popups';
        value: number | Popup;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  publishedAt?: T;
  author?: T;
  coverImage?: T;
  category?: T;
  content?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              alt?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              url?: T;
              caption?: T;
              autoplay?: T;
              id?: T;
              blockName?: T;
            };
        gif?:
          | T
          | {
              gif?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              author?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  coverImage?: T;
  client?: T;
  tag?: T;
  headline?: T;
  situation?: T;
  action?: T;
  result?: T;
  ctaLabel?: T;
  ctaLink?: T;
  hasVideo?: T;
  videoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  photo?: T;
  bio?: T;
  linkedin?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-config_select".
 */
export interface CtaConfigSelect<T extends boolean = true> {
  title?: T;
  email?:
    | T
    | {
        to?: T;
        from?: T;
        subject?: T;
        htmlContent?: T;
        body?: T;
        headers?:
          | T
          | {
              key?: T;
              value?: T;
              id?: T;
            };
        attachments?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups_select".
 */
export interface PopupsSelect<T extends boolean = true> {
  name?: T;
  isActive?: T;
  scheduling?:
    | T
    | {
        startDate?: T;
        endDate?: T;
      };
  display?:
    | T
    | {
        pages?: T;
        specificPaths?:
          | T
          | {
              path?: T;
              id?: T;
            };
        delay?: T;
        frequency?: T;
      };
  content?:
    | T
    | {
        badge?: T;
        title?: T;
        body?: T;
        image?: T;
      };
  buttons?:
    | T
    | {
        label?: T;
        action?: T;
        url?: T;
        openInNewTab?: T;
        style?: T;
        id?: T;
      };
  registration?:
    | T
    | {
        notifyEmail?: T;
        emailSubject?: T;
        collectName?: T;
        collectPhone?: T;
        collectOrganization?: T;
        successMessage?: T;
      };
  appearance?:
    | T
    | {
        size?: T;
        showCloseButton?: T;
        closeOnOverlayClick?: T;
        badgeColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  company?: T;
  email?: T;
  challenge?: T;
  sourceSection?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo-wall".
 */
export interface LogoWall {
  id: number;
  agribusinessLogos?:
    | {
        name: string;
        image?: (number | null) | Media;
        /**
         * Optional URL — clicking the logo will open this link in a new tab.
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  bankLogos?:
    | {
        name: string;
        image?: (number | null) | Media;
        /**
         * Optional URL — clicking the logo will open this link in a new tab.
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "voice-of-customer".
 */
export interface VoiceOfCustomer {
  id: number;
  quotes?:
    | {
        quote: string;
        name: string;
        role: string;
        /**
         * e.g. "Bank Partner", "Agribusiness CEO"
         */
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo-wall_select".
 */
export interface LogoWallSelect<T extends boolean = true> {
  agribusinessLogos?:
    | T
    | {
        name?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  bankLogos?:
    | T
    | {
        name?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "voice-of-customer_select".
 */
export interface VoiceOfCustomerSelect<T extends boolean = true> {
  quotes?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}